services:

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always

    ports:
      - "8080:8080"
      - "50000:50000"

    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./allure-results:/allure-results
      - ./allure-reports:/allure-reports
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

    user: root

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb

    ports:
      - "5433:5432"   # 🔥 CORREÇÃO AQUI

    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  allure:
    image: frankescobar/allure-docker-service
    container_name: allure
    restart: always

    ports:
      - "5050:5050"

    environment:
      CHECK_RESULTS_EVERY_SECONDS: 3
      KEEP_HISTORY: 1

    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-reports:/app/default-reports